apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: c2c-prod-namespace
  # annotations:
  #   kubernetes.io/ingress.class: azure/application-gateway
spec:
  ingressClassName: azure-application-gateway
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: svc-master
            port:
              number: 8000
        pathType: Exact