apiVersion: v1
kind: Service
metadata:
  name: mul-svc
  namespace: c2c-prod-namespace
  labels:
    app: ms-mul
spec:
  selector:
    app: ms-mul
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
  type: ClusterIP
