apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-auth
  namespace: c2c-prod-namespace
spec:
  selector:
    matchLabels:
      app: ms-auth
  template:
    metadata:
      labels:
        app: ms-auth
    spec:
      serviceAccountName: "workload-identity-sa"
      volumes:
          - name: secrets-store01-inline
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: "c2c-prod-namespace"
      containers:
      - name: ms-auth
        image: brlregistrity.azurecr.io/c2c-auth:55f995b
        resources:
          requests:
            cpu: 80m
            memory: 256Mi
          limits:
            cpu: 100m
            memory: 500Mi
        volumeMounts:
          - name: secrets-store01-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
        ports:
        - containerPort: 8001
