apiVersion: v1
items:
- apiVersion: secrets-store.csi.x-k8s.io/v1
  kind: SecretProviderClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"secrets-store.csi.x-k8s.io/v1","kind":"SecretProviderClass","metadata":{"annotations":{},"name":"c2c-prod-namespace","namespace":"c2c-prod-namespace"},"spec":{"parameters":{"clientID":"7d48cf86-36dd-4f77-959f-f5e396334826","cloudName":"","keyvaultName":"c2c-prod-vault","objects":"array:\n  - |\n    objectName: secret1             # Set to the name of your secret\n    objectType: secret              # object types: secret, key, or cert\n    objectVersion: \"\"               # [OPTIONAL] object versions, default to latest if empty\n","tenantId":"c7d884f9-0fc9-43c7-8491-a7690ea021f5","usePodIdentity":"false"},"provider":"azure"}}
    creationTimestamp: "2024-07-26T20:14:22Z"
    generation: 1
    name: c2c-prod-namespace
    namespace: c2c-prod-namespace
    resourceVersion: "316244"
    uid: f784e093-9052-455e-a1fc-a99a3d73845f
  spec:
    parameters:
      clientID: 7d48cf86-36dd-4f77-959f-f5e396334826
      cloudName: ""
      keyvaultName: c2c-prod-vault
      objects: |
        array:
        - |-
          objectName: DB-HOSTNAME
          objectType: secret
          objectVersion: ""
        - |-
          objectName: DB-PASSWORD
          objectType: secret
          objectVersion: ""
        - |-
          objectName: DB-PORT
          objectType: secret
          objectVersion: ""
        - |-
          objectName: DB-USERNAME
          objectType: secret
          objectVersion: ""
      tenantId: c7d884f9-0fc9-43c7-8491-a7690ea021f5
      usePodIdentity: "false"
    provider: azure
kind: List
metadata:
  resourceVersion: ""